### ISSUE TITLE
Problem about missing module "customconfig"

### ISSUE THREAD

**Issue by leonsylarfang** [IHe-KaiI/DressCode#10]
Dear Kai,

I tried to run `python nn/train.py` according to your instructions on _README.md_, after all the requirements had been installed.
However, I encountered an error: "ModuleNotFoundError: No module named 'customconfig'" on line 9. 
<img width="724" alt="微信图片_20240904101010" src="https://github.com/user-attachments/assets/07a9c239-d726-406f-8be0-eefa6b8f4c9e">

After searching all the files of this project, I did not get where the definition is written. Besides, while checking all the issues, it seems like no one had the same problem as me.

Could you please help me with this? Please forgive me if it is a problem that is too basic.

Best,
Junheng

**Comment by louis-fashion-ai** [comment]
Please tell me how do you solve it? I encountered the same problem.

**Comment by Emir-Liu** [comment]
![image](https://github.com/user-attachments/assets/9b0c49ba-e943-4de4-bf1a-ffd2e3152b02)

Environmental variable
Add ./packages to PYTHONPATH for importing custom modules.
