### ISSUE TITLE
Probably a bug in training code during data loading

### ISSUE THREAD

**Issue by NagabhushanSN24** [IHe-KaiI/DressCode#11]
Hi,

In `datasets.py`, in [line 646](https://github.com/IHe-KaiI/DressCode/blob/main/nn/data/datasets.py#L646), you're querying `batch['features']`, but in [`__get_item__()`](https://github.com/IHe-KaiI/DressCode/blob/main/nn/data/datasets.py#L128), you're unwrapping `features` dict and providing only the `captions`. 

Can you please check this?

**Comment by IHe-KaiI** [comment]
Hi NagabhushanSN24, 

Thanks for your comments! It seems we didn't clear some unnecessary code in ```datasets.py``` when built upon the NeuralTailor. ```batch['features']``` are used to load point clouds in NeuralTailor, and in our setting, we only load ```captions``` as ```features``` (see [line 852](https://github.com/IHe-KaiI/DressCode/blob/5f8d657b1feed4e8b766d528170d1ca94c67c3b7/nn/data/datasets.py#L852)).

**Comment by NagabhushanSN24** [comment]
Got it, thanks @IHe-KaiI for the reply. So, should line 646 be changed from `batch['features']` to `batch['captions']`?

**Comment by IHe-KaiI** [comment]
> Got it, thanks @IHe-KaiI for the reply. So, should line 646 be changed from `batch['features']` to `batch['captions']`?

You can simply delete it or leave it alone since we wrote hardcode [here](https://github.com/IHe-KaiI/DressCode/blob/5f8d657b1feed4e8b766d528170d1ca94c67c3b7/nn/data/transforms.py#L43).

**Comment by NagabhushanSN24** [comment]
Ah okay!
