### ISSUE TITLE
Please explain the values 120 and 30 in SewingGPT embedding layer dimensions

### ISSUE THREAD

**Issue by NagabhushanSN24** [IHe-KaiI/DressCode#12]
Hi,

Can you please explain the meaning of the values `120` and `30` in [SewingGPT](https://github.com/IHe-KaiI/DressCode/blob/main/nn/nets.py#L39--L40) definition? I mean how did you arrive at these numbers? What do they represent?

**Comment by IHe-KaiI** [comment]
The maximum possible value for the ```nn.Embedding```, similar to ```vocab_size``` for ```value_emb```.
