### ISSUE TITLE
do I have to install maya on linux?

### ISSUE THREAD

**Issue by derrick-xwp** [IHe-KaiI/DressCode#5]
maya needs license

**Comment by IHe-KaiI** [comment]
Thanks for your interest. Maya is necessary for simulation. You don't need to install Maya if you don't need the simulated 3D model.

**Comment by NagabhushanSN24** [comment]
@derrick-xwp you can check this out for ubuntu: https://www.autodesk.com/support/technical/article/caas/tsarticles/ts/5ZZjP3R0R7hzPyhDYkd8IS.html
