### ISSUE TITLE
How to train DressCode on a different dataset?

### ISSUE THREAD

**Issue by NagabhushanSN24** [IHe-KaiI/DressCode#9]
Hi,

I would like to train DressCode on a more recent dataset: [GarmentCodeData: A Dataset of 3D Made-to-Measure Garments With Sewing Patterns](https://arxiv.org/abs/2405.17609). Can you please share/release the code to generate text captions for a new dataset?

**Comment by IHe-KaiI** [comment]
Please refer to the prompts [here](https://github.com/IHe-KaiI/DressCode/blob/main/docs/GPT4V-prompt.md).

**Comment by NagabhushanSN24** [comment]
Thank you very much for the quick reply.
